### ISSUE TITLE
Ubuntu Upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/tutor#1113]
Open edX Upstream will be upgrading Ubuntu to 22.04 or 24.04 for Sumac https://github.com/openedx/platform-roadmap/issues/377. The current running version, 20.04, will reach its end of life in February 2025. Since Upstream is moving Ubuntu, it is necessary to move tutor and its plugins to the same version of Ubuntu, where applicable, to ensure the base OS in tutor is the same as Upstream. 

### General Guidelines
- Please make sure any issue encountered in the tutor, be it due to tutor or the upstream service, is documented on this main issue.
- To tackle the upgrade, you can start with existing test suites upgrade/compatibility by using ubuntu-latest for Github Actions. If the tests are passing, you can move to Dockerfile update.
- To make sure that changes are working as expected, ensure the following where needed
  - verify that the images are built correctly
    -  You might need to re-test once upstream has moved to new Ubuntu version
- Because these changes are meant for Sumac, we would be adding these to **nightly**

Do not hesitate to ask for help, guidance, and/or clarity where needed.

### Action Items
- Ensure the build is working as expected (core or plugins) with Dockerfile updates

#### Require re-testing on Upstream changes
- [x] Tutor (https://github.com/overhangio/tutor/issues/1114 -- @DawoudSheraz )
- [x] Tutor-credentials (https://github.com/overhangio/tutor-credentials/issues/45 -- @Faraz32123 )
- [x] tutor-notes (https://github.com/overhangio/tutor-notes/issues/38 -- @jfavellar90)
- [x] tutor-xqueue (https://github.com/overhangio/tutor-xqueue/issues/32 -- @jfavellar90)
- [x] scorm-xblock (https://github.com/overhangio/openedx-scorm-xblock/issues/82 -- @Danyal-Faheem )
- [x] tutor-discovery (https://github.com/overhangio/tutor-discovery/issues/83 -- @hinakhadim )

#### Not Dependent Directly on Upstream
- [x] tutor-android (https://github.com/overhangio/tutor-android/issues/25 -- @muhammadali286 )

**Comment by DawoudSheraz** [comment]
All link items have been completed, closing this issue.
